/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APAllocateTransactionsPostRequest
 */
export interface APAllocateTransactionsPostRequest {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof APAllocateTransactionsPostRequest
     */
    'CreditID': number;
    /**
     * 
     * @type {number}
     * @memberof APAllocateTransactionsPostRequest
     */
    'DebitID': number;
    /**
     * 
     * @type {number}
     * @memberof APAllocateTransactionsPostRequest
     */
    'AllocationAmount': number;
    /**
     * 
     * @type {string}
     * @memberof APAllocateTransactionsPostRequest
     */
    'AllocationDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof APAllocateTransactionsPostRequest
     */
    'DiscountAmount'?: number;
}

