/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APCreditorGroup
 */
export interface APCreditorGroup {
    /**
     * 
     * @type {number}
     * @memberof APCreditorGroup
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'CreditorGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'CreditorGroupName'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'GLCreditorAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'GLDiscountAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'DefaultBankAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'DefaultPaymentMethod'?: APCreditorGroupDefaultPaymentMethodEnum;
    /**
     * 
     * @type {number}
     * @memberof APCreditorGroup
     */
    'PaymentCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'PaymentUnit'?: APCreditorGroupPaymentUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof APCreditorGroup
     */
    'PaymentDayOfMonth'?: number;
    /**
     * 
     * @type {number}
     * @memberof APCreditorGroup
     */
    'Discount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APCreditorGroup
     */
    'DiscountCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'DiscountUnit'?: APCreditorGroupDiscountUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof APCreditorGroup
     */
    'DiscountDayOfMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'DefaultGSTOverride'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'EASCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'DefaultRegimeCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof APCreditorGroup
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof APCreditorGroup
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof APCreditorGroup
     */
    '@odata.etag'?: string;
}

export const APCreditorGroupDefaultPaymentMethodEnum = {
    ComputerPrintedCheque: 'Computer Printed Cheque',
    CreditCard: 'Credit Card',
    DirectDebit: 'Direct Debit',
    Electronic: 'Electronic',
    LetterOfCredit: 'Letter of Credit',
    Manual: 'Manual',
    Remittance: 'Remittance',
    TelegraphicTransfer: 'Telegraphic Transfer'
} as const;

export type APCreditorGroupDefaultPaymentMethodEnum = typeof APCreditorGroupDefaultPaymentMethodEnum[keyof typeof APCreditorGroupDefaultPaymentMethodEnum];
export const APCreditorGroupPaymentUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months'
} as const;

export type APCreditorGroupPaymentUnitEnum = typeof APCreditorGroupPaymentUnitEnum[keyof typeof APCreditorGroupPaymentUnitEnum];
export const APCreditorGroupDiscountUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months'
} as const;

export type APCreditorGroupDiscountUnitEnum = typeof APCreditorGroupDiscountUnitEnum[keyof typeof APCreditorGroupDiscountUnitEnum];


