/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APExpenseBudgetBudgets
 */
export interface APExpenseBudgetBudgets {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof APExpenseBudgetBudgets
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof APExpenseBudgetBudgets
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof APExpenseBudgetBudgets
     */
    'PeriodName'?: string;
    /**
     * 
     * @type {number}
     * @memberof APExpenseBudgetBudgets
     */
    'LastYearPeriod'?: number;
    /**
     * 
     * @type {number}
     * @memberof APExpenseBudgetBudgets
     */
    'LastYearBudget'?: number;
    /**
     * 
     * @type {number}
     * @memberof APExpenseBudgetBudgets
     */
    'Period'?: number;
    /**
     * 
     * @type {number}
     * @memberof APExpenseBudgetBudgets
     */
    'Budget'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof APExpenseBudgetBudgets
     */
    'Adjustment'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APExpenseBudgetBudgets
     */
    '@odata.etag'?: string;
}

