/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APShipmentsLineTracking
 */
export interface APShipmentsLineTracking {
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'DetailID'?: number;
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'LineNo'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof APShipmentsLineTracking
     */
    'Pending'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APShipmentsLineTracking
     */
    'BinCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APShipmentsLineTracking
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof APShipmentsLineTracking
     */
    'LotNo'?: string;
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'Quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof APShipmentsLineTracking
     */
    'ExpiryDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof APShipmentsLineTracking
     */
    'LotDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof APShipmentsLineTracking
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof APShipmentsLineTracking
     */
    'FixedLot'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'SourceID'?: number;
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'SourceLineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof APShipmentsLineTracking
     */
    'Class'?: APShipmentsLineTrackingClassEnum;
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof APShipmentsLineTracking
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof APShipmentsLineTracking
     */
    'Contra'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APShipmentsLineTracking
     */
    '@odata.etag'?: string;
}

export const APShipmentsLineTrackingClassEnum = {
    Allocation: 'Allocation',
    TransferOut: 'Transfer Out',
    Variation: 'Variation',
    TransferIn: 'Transfer In',
    Shipped: 'Shipped',
    Commitment: 'Commitment',
    Returned: 'Returned',
    WriteOff: 'Write Off',
    InProduction: 'In Production'
} as const;

export type APShipmentsLineTrackingClassEnum = typeof APShipmentsLineTrackingClassEnum[keyof typeof APShipmentsLineTrackingClassEnum];


