/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface APTransactionList
 */
export interface APTransactionList {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'Reference'?: string;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'PeriodName'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'BillFromAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'TransactionType'?: APTransactionListTransactionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'SourceID'?: number;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'DueDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'DiscountDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'TransactionAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'DebitAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'CreditAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'UnallocatedAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'TransactionDiscount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'UnallocatedDiscount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'PeriodFullyAllocated'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'GstIncluded'?: number;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'GLAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'PaymentMethod'?: APTransactionListPaymentMethodEnum;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'ApprovalAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'ApprovalDiscount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'HoldAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'ExclusiveAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'PrintStatus'?: APTransactionListPrintStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof APTransactionList
     */
    'PaymentCreated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'OriginationDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'DefaultJobCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'OrderNos'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof APTransactionList
     */
    'HasLinks'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof APTransactionList
     */
    'HasMemos'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'RegimeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'Narration'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'RateType'?: string;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'ExchangeRate'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof APTransactionList
     */
    'FixedRate'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'eInvoiceIdentifier'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'GstIncludedBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'TransactionDiscountBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'TransactionAmountBs'?: number;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'DateFullyPaid'?: string;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'VariationRealisedBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'VariationUnrealisedBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'UnallocatedAmountBs'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof APTransactionList
     */
    'TransferredToGL'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    'ReferenceAlpha'?: string;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'ExchangeRateRaw'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'ExclusiveAmountBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'VariationBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'NetAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'NetAmountBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof APTransactionList
     */
    'DaysToPay'?: number;
    /**
     * 
     * @type {string}
     * @memberof APTransactionList
     */
    '@odata.etag'?: string;
}

export const APTransactionListTransactionTypeEnum = {
    Invoice: 'Invoice',
    Credit: 'Credit',
    Payment: 'Payment',
    Journal: 'Journal'
} as const;

export type APTransactionListTransactionTypeEnum = typeof APTransactionListTransactionTypeEnum[keyof typeof APTransactionListTransactionTypeEnum];
export const APTransactionListPaymentMethodEnum = {
    ComputerPrintedCheque: 'Computer Printed Cheque',
    CreditCard: 'Credit Card',
    DirectDebit: 'Direct Debit',
    Electronic: 'Electronic',
    LetterOfCredit: 'Letter of Credit',
    Manual: 'Manual',
    Remittance: 'Remittance',
    TelegraphicTransfer: 'Telegraphic Transfer'
} as const;

export type APTransactionListPaymentMethodEnum = typeof APTransactionListPaymentMethodEnum[keyof typeof APTransactionListPaymentMethodEnum];
export const APTransactionListPrintStatusEnum = {
    Empty: '',
    Unprinted: 'Unprinted',
    Printed: 'Printed'
} as const;

export type APTransactionListPrintStatusEnum = typeof APTransactionListPrintStatusEnum[keyof typeof APTransactionListPrintStatusEnum];


