/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ARContact
 */
export interface ARContact {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof ARContact
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof ARContact
     */
    'ContactID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'CustomerCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ARContact
     */
    'IsPrimary'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'Title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'FirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'MiddleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'LastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'Suffix'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'FirstNameLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'LastNameFirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'Role'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'EmailAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'PhoneNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'PhoneNo2'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'PhoneNo3'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'Custom2'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ARContact
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'FullName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof ARContact
     */
    'LineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof ARContact
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'ContactName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ARContact
     */
    'PrimaryContact'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'AccountFile'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARContact
     */
    '@odata.etag'?: string;
}

