/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ARSalesPersonBudgetBudgets } from './arsales-person-budget-budgets';

/**
 * 
 * @export
 * @interface ARSalesPersonBudget
 */
export interface ARSalesPersonBudget {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof ARSalesPersonBudget
     */
    'RecNo'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ARSalesPersonBudget
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ARSalesPersonBudget
     */
    'SalesPersonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ARSalesPersonBudget
     */
    'SalesPersonName'?: string;
    /**
     * 
     * @type {Array<ARSalesPersonBudgetBudgets>}
     * @memberof ARSalesPersonBudget
     */
    'Budgets'?: Array<ARSalesPersonBudgetBudgets>;
    /**
     * 
     * @type {number}
     * @memberof ARSalesPersonBudget
     */
    'YearNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ARSalesPersonBudget
     */
    '@odata.etag'?: string;
}

