/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FATransactionList
 */
export interface FATransactionList {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'AssetCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'Reference'?: string;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'PeriodName'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'TransactionType'?: FATransactionListTransactionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'BookAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'DebitAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'CreditAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'AdjustmentAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'DepreciationCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'DepreciationRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'TransactionQuantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'Narration'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'SourceID'?: number;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'SourceLineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'GLAccountCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FATransactionList
     */
    'Generated'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FATransactionList
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FATransactionList
     */
    'HasLinks'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FATransactionList
     */
    'HasMemos'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FATransactionList
     */
    'TransferredToGL'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof FATransactionList
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof FATransactionList
     */
    '@odata.etag'?: string;
}

export const FATransactionListTransactionTypeEnum = {
    Addition: 'Addition',
    Depreciation: 'Depreciation',
    Revaluation: 'Revaluation',
    Disposal: 'Disposal',
    Adjustment: 'Adjustment'
} as const;

export type FATransactionListTransactionTypeEnum = typeof FATransactionListTransactionTypeEnum[keyof typeof FATransactionListTransactionTypeEnum];


