/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GLTransactionList
 */
export interface GLTransactionList {
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'Reference'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'PeriodName'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'Comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'TransactionAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'Debit'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'Credit'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'BatchID'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'SourceID'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'SourceLineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'Narration'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'CompanyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'BatchClass'?: GLTransactionListBatchClassEnum;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'SourceCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'ReconciliationID'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'ReconciliationLineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'PeriodReconciled'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransactionList
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    'ReferenceAlpha'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GLTransactionList
     */
    'Reconciled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GLTransactionList
     */
    '@odata.etag'?: string;
}

export const GLTransactionListBatchClassEnum = {
    GlBatch: 'GL Batch',
    ModuleBatch: 'Module Batch',
    ReversingJournal: 'Reversing Journal',
    StandingJournal: 'Standing Journal',
    TemplateBatch: 'Template Batch',
    ReversingOut: 'Reversing Out',
    Imported: 'Imported'
} as const;

export type GLTransactionListBatchClassEnum = typeof GLTransactionListBatchClassEnum[keyof typeof GLTransactionListBatchClassEnum];


