/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GLTransaction
 */
export interface GLTransaction {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'Comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'TransactionAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'SourceID'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'Narration'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'SourceLineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'SourceCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'ReconciliationID'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'ReconciliationLineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'PeriodReconciled'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof GLTransaction
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    'ReferenceAlpha'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GLTransaction
     */
    'Reconciled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GLTransaction
     */
    '@odata.etag'?: string;
}

