/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ICAdjustmentBatchLink
 */
export interface ICAdjustmentBatchLink {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof ICAdjustmentBatchLink
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICAdjustmentBatchLink
     */
    'LinkID'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICAdjustmentBatchLink
     */
    'ImageIndex'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'LinkType'?: ICAdjustmentBatchLinkLinkTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'FilePath'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'Comment'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICAdjustmentBatchLink
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'LastModified'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICAdjustmentBatchLink
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    'ShortFileName'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICAdjustmentBatchLink
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICAdjustmentBatchLink
     */
    '@odata.etag'?: string;
}

export const ICAdjustmentBatchLinkLinkTypeEnum = {
    File: 'File',
    Web: 'Web'
} as const;

export type ICAdjustmentBatchLinkLinkTypeEnum = typeof ICAdjustmentBatchLinkLinkTypeEnum[keyof typeof ICAdjustmentBatchLinkLinkTypeEnum];


