/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICBinCountLine } from './icbin-count-line';
// May contain unused imports in some cases
// @ts-ignore
import { ICBinCountLink } from './icbin-count-link';

/**
 * 
 * @export
 * @interface ICBinCount
 */
export interface ICBinCount {
    /**
     * 
     * @type {number}
     * @memberof ICBinCount
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICBinCount
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'Details'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'StorePersonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'PrintStatus'?: ICBinCountPrintStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'PostStatus'?: ICBinCountPostStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'SourceType'?: ICBinCountSourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'BaseUOMCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'Unit'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICBinCount
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'BinCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'BinName'?: string;
    /**
     * 
     * @type {Array<ICBinCountLine>}
     * @memberof ICBinCount
     */
    'Line'?: Array<ICBinCountLine>;
    /**
     * 
     * @type {number}
     * @memberof ICBinCount
     */
    'RecNo'?: number;
    /**
     * 
     * @type {Array<ICBinCountLink>}
     * @memberof ICBinCount
     */
    'Link'?: Array<ICBinCountLink>;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'AccountFile'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCount
     */
    '@odata.etag'?: string;
}

export const ICBinCountPrintStatusEnum = {
    Unprinted: 'Unprinted',
    Printed: 'Printed'
} as const;

export type ICBinCountPrintStatusEnum = typeof ICBinCountPrintStatusEnum[keyof typeof ICBinCountPrintStatusEnum];
export const ICBinCountPostStatusEnum = {
    Uncounted: 'Uncounted',
    Counted: 'Counted',
    Posted: 'Posted',
    Deleted: 'Deleted'
} as const;

export type ICBinCountPostStatusEnum = typeof ICBinCountPostStatusEnum[keyof typeof ICBinCountPostStatusEnum];
export const ICBinCountSourceTypeEnum = {
    Invoice: 'Invoice',
    Credit: 'Credit',
    Shipment: 'Shipment',
    Transfer: 'Transfer',
    Stocktake: 'Stocktake',
    Job: 'Job',
    Manufacture: 'Manufacture',
    SalesOrder: 'Sales Order',
    PurchaseOrder: 'Purchase Order',
    AdjustmentBatch: 'Adjustment Batch',
    WriteOff: 'Write Off',
    ReceiptBatch: 'Receipt Batch',
    BinMovement: 'Bin Movement',
    BinCount: 'Bin Count'
} as const;

export type ICBinCountSourceTypeEnum = typeof ICBinCountSourceTypeEnum[keyof typeof ICBinCountSourceTypeEnum];


