/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICBinCountLineTracking } from './icbin-count-line-tracking';

/**
 * 
 * @export
 * @interface ICBinCountLine
 */
export interface ICBinCountLine {
    /**
     * 
     * @type {number}
     * @memberof ICBinCountLine
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICBinCountLine
     */
    'LineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICBinCountLine
     */
    'LineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'Description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICBinCountLine
     */
    'QuantityCounted'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'Unit'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'LotDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'ExpiryDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'LotNo'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICBinCountLine
     */
    'Adjust'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ICBinCountLine
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'TrackingRequired'?: ICBinCountLineTrackingRequiredEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ICBinCountLine
     */
    'ExpiryDateTracked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'SerialTracked'?: ICBinCountLineSerialTrackedEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ICBinCountLine
     */
    'LotTracked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICBinCountLine
     */
    'QuantityExpected'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICBinCountLine
     */
    'QuantityVariance'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ICBinCountLine
     */
    'ExistingSerialNo'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICBinCountLine
     */
    'ExistingLotNo'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    'SerialBinCode'?: string;
    /**
     * 
     * @type {Array<ICBinCountLineTracking>}
     * @memberof ICBinCountLine
     */
    'Tracking'?: Array<ICBinCountLineTracking>;
    /**
     * 
     * @type {string}
     * @memberof ICBinCountLine
     */
    '@odata.etag'?: string;
}

export const ICBinCountLineTrackingRequiredEnum = {
    None: 'None',
    Complete: 'Complete',
    Incomplete: 'Incomplete'
} as const;

export type ICBinCountLineTrackingRequiredEnum = typeof ICBinCountLineTrackingRequiredEnum[keyof typeof ICBinCountLineTrackingRequiredEnum];
export const ICBinCountLineSerialTrackedEnum = {
    None: 'None',
    Sale: 'Sale',
    Purchase: 'Purchase'
} as const;

export type ICBinCountLineSerialTrackedEnum = typeof ICBinCountLineSerialTrackedEnum[keyof typeof ICBinCountLineSerialTrackedEnum];


