/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICBinMovementLine } from './icbin-movement-line';
// May contain unused imports in some cases
// @ts-ignore
import { ICBinMovementLink } from './icbin-movement-link';

/**
 * 
 * @export
 * @interface ICBinMovement
 */
export interface ICBinMovement {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof ICBinMovement
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICBinMovement
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'Details'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'StorePersonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'PrintStatus'?: ICBinMovementPrintStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'PostStatus'?: ICBinMovementPostStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'SourceType'?: ICBinMovementSourceTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'BaseUOMCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'Unit'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICBinMovement
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'BinCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'BatchClass'?: ICBinMovementBatchClassEnum;
    /**
     * 
     * @type {Array<ICBinMovementLine>}
     * @memberof ICBinMovement
     */
    'Line'?: Array<ICBinMovementLine>;
    /**
     * 
     * @type {number}
     * @memberof ICBinMovement
     */
    'RecNo'?: number;
    /**
     * 
     * @type {Array<ICBinMovementLink>}
     * @memberof ICBinMovement
     */
    'Link'?: Array<ICBinMovementLink>;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'AccountFile'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICBinMovement
     */
    '@odata.etag'?: string;
}

export const ICBinMovementPrintStatusEnum = {
    Unprinted: 'Unprinted',
    Printed: 'Printed'
} as const;

export type ICBinMovementPrintStatusEnum = typeof ICBinMovementPrintStatusEnum[keyof typeof ICBinMovementPrintStatusEnum];
export const ICBinMovementPostStatusEnum = {
    Unposted: 'Unposted',
    Open: 'Open',
    Posted: 'Posted',
    Deleted: 'Deleted'
} as const;

export type ICBinMovementPostStatusEnum = typeof ICBinMovementPostStatusEnum[keyof typeof ICBinMovementPostStatusEnum];
export const ICBinMovementSourceTypeEnum = {
    Invoice: 'Invoice',
    Credit: 'Credit',
    Shipment: 'Shipment',
    Transfer: 'Transfer',
    Stocktake: 'Stocktake',
    Job: 'Job',
    Manufacture: 'Manufacture',
    SalesOrder: 'Sales Order',
    PurchaseOrder: 'Purchase Order',
    AdjustmentBatch: 'Adjustment Batch',
    WriteOff: 'Write Off',
    ReceiptBatch: 'Receipt Batch',
    BinMovement: 'Bin Movement',
    BinCount: 'Bin Count'
} as const;

export type ICBinMovementSourceTypeEnum = typeof ICBinMovementSourceTypeEnum[keyof typeof ICBinMovementSourceTypeEnum];
export const ICBinMovementBatchClassEnum = {
    PutAway: 'Put-away',
    Pick: 'Pick'
} as const;

export type ICBinMovementBatchClassEnum = typeof ICBinMovementBatchClassEnum[keyof typeof ICBinMovementBatchClassEnum];


