/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICComponentPart } from './iccomponent-part';
// May contain unused imports in some cases
// @ts-ignore
import { ICComponentPrice } from './iccomponent-price';

/**
 * 
 * @export
 * @interface ICComponent
 */
export interface ICComponent {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'RecNo'?: number;
    /**
     * 
     * @type {Array<ICComponentPart>}
     * @memberof ICComponent
     */
    'Part'?: Array<ICComponentPart>;
    /**
     * 
     * @type {Array<ICComponentPrice>}
     * @memberof ICComponent
     */
    'Price'?: Array<ICComponentPrice>;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'AutomaticSubcomponent'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ComponentFunction'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ExpiryUnit'?: ICComponentExpiryUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'ExpiryCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SerialNoPrefix'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SerialNoCounter'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SerialNoSuffix'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'TotalAverageCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'TotalLatestCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'TotalStandardCost'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'Description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ComponentMode'?: ICComponentComponentModeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'NonDiminishing'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'StandardCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'LatestCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'AverageCost'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SellCurrencyCode1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SellCurrencyCode2'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SellCurrencyCode3'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SellCurrencyCode4'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SellCurrencyCode5'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SellCurrencyCode6'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SellCurrencyCode7'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SellCurrencyCode8'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SellCurrencyCode9'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SellingPrice1'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SellingPrice2'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SellingPrice3'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SellingPrice4'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SellingPrice5'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SellingPrice6'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SellingPrice7'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SellingPrice8'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SellingPrice9'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'HasParts'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'AlternateCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'Details'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'BarCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'Unit'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'GstCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'DiscountScheduleCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'StockGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SalesGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'LeadTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'Weight'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'Volume'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'ManuallyCosted'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'CommissionPercentage'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'BackOrder'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'Comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarkupPercent1'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarkupPercent2'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarkupPercent3'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarkupPercent4'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarkupPercent5'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarkupPercent6'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarkupPercent7'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarkupPercent8'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarkupPercent9'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ImagePath'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MinimumQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MaximumQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'OpeningStockPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SalesQuantityPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'ReceiptsPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'AdjustmentsPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'UsagePeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'ManufacturedPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'NonDiminishingPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SalesValuePeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'CostOfSalesPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'CostValuePeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'OpeningStockYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SalesQuantityYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'ReceiptsYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'UsageYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'AdjustmentsYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'ManufacturedYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'NonDiminishingYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SalesValueYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'CostOfSalesYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'CostValueYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'StocktakeVariance'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityOnOrder'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityAllocated'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityOnBackOrder'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityInStock'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityCommitted'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'DateOfLastSale'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'DateOfLastUsage'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'DateOfLastReceipt'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'DateOfLastManufacture'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'Duty'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityShipped'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'BaseUOMCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SerialTracked'?: ICComponentSerialTrackedEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'ExpiryDateTracked'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'SerialNoLength'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'MinimumExpiryUnit'?: ICComponentMinimumExpiryUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MinimumExpiryCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'LastHistoryPeriod'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'HasRegimeOverrides'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'Discontinued'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'SaleUOMCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'PurchaseUOMCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ImageType'?: ICComponentImageTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ExpenseCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'JCTransactionType'?: ICComponentJCTransactionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'CostCentreCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'ComponentCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'LotTracked'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'LotNoLength'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'SupplySingleLot'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'GenerateLotNos'?: ICComponentGenerateLotNosEnum;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'RetainYearsTracking'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'EditRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    'DateOfLastStocktake'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'RevaluationPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'RevaluationYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityReturned'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityTransferIn'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityTransferOut'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityInProduction'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'ClosingPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'ClosingYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarginPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'MarginYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityAvailable'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityTheoretical'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICComponent
     */
    'QuantityRecReorder'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ICComponent
     */
    'IsTracked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICComponent
     */
    '@odata.etag'?: string;
}

export const ICComponentExpiryUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months',
    Years: 'Years'
} as const;

export type ICComponentExpiryUnitEnum = typeof ICComponentExpiryUnitEnum[keyof typeof ICComponentExpiryUnitEnum];
export const ICComponentComponentModeEnum = {
    None: 'None',
    AutomaticKitset: 'Automatic Kitset',
    ManualKitset: 'Manual Kitset',
    Manufacture: 'Manufacture'
} as const;

export type ICComponentComponentModeEnum = typeof ICComponentComponentModeEnum[keyof typeof ICComponentComponentModeEnum];
export const ICComponentSerialTrackedEnum = {
    None: 'None',
    Sale: 'Sale',
    Purchase: 'Purchase'
} as const;

export type ICComponentSerialTrackedEnum = typeof ICComponentSerialTrackedEnum[keyof typeof ICComponentSerialTrackedEnum];
export const ICComponentMinimumExpiryUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months',
    Years: 'Years'
} as const;

export type ICComponentMinimumExpiryUnitEnum = typeof ICComponentMinimumExpiryUnitEnum[keyof typeof ICComponentMinimumExpiryUnitEnum];
export const ICComponentImageTypeEnum = {
    File: 'File',
    Web: 'Web'
} as const;

export type ICComponentImageTypeEnum = typeof ICComponentImageTypeEnum[keyof typeof ICComponentImageTypeEnum];
export const ICComponentJCTransactionTypeEnum = {
    Time: 'Time',
    Material: 'Material',
    Disbursement: 'Disbursement',
    Narrative: 'Narrative'
} as const;

export type ICComponentJCTransactionTypeEnum = typeof ICComponentJCTransactionTypeEnum[keyof typeof ICComponentJCTransactionTypeEnum];
export const ICComponentGenerateLotNosEnum = {
    None: 'None',
    ExpiryDate: 'Expiry Date',
    LotDate: 'Lot Date'
} as const;

export type ICComponentGenerateLotNosEnum = typeof ICComponentGenerateLotNosEnum[keyof typeof ICComponentGenerateLotNosEnum];


