/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICManufactureBatchLineTracking } from './icmanufacture-batch-line-tracking';

/**
 * 
 * @export
 * @interface ICManufactureBatchLine
 */
export interface ICManufactureBatchLine {
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'PartType'?: ICManufactureBatchLinePartTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'Description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'TransactionQuantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'UnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'CostValueExclusive'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'Unit'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'LineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'LotNo'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICManufactureBatchLine
     */
    'LineBreak'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICManufactureBatchLine
     */
    'LineSpace'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'Custom2'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'TrackingRequired'?: ICManufactureBatchLineTrackingRequiredEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ICManufactureBatchLine
     */
    'ExpiryDateTracked'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICManufactureBatchLine
     */
    'Subcomponent'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'AlternateCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'BarCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    'BinCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityInStock'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityAllocated'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityAvailable'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityOnBackOrder'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityShipped'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityOnOrder'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityCommitted'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityReturned'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityInProduction'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityTransferOut'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityTransferIn'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityInTransit'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'Weight'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'Volume'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'ExtendedWeight'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'ExtendedVolume'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'MinimumQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'MaximumQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityTheoretical'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'StocktakeVariance'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICManufactureBatchLine
     */
    'QuantityRecReorder'?: number;
    /**
     * 
     * @type {Array<ICManufactureBatchLineTracking>}
     * @memberof ICManufactureBatchLine
     */
    'Tracking'?: Array<ICManufactureBatchLineTracking>;
    /**
     * 
     * @type {string}
     * @memberof ICManufactureBatchLine
     */
    '@odata.etag'?: string;
}

export const ICManufactureBatchLinePartTypeEnum = {
    Variable: 'Variable',
    Fixed: 'Fixed',
    Narrative: 'Narrative'
} as const;

export type ICManufactureBatchLinePartTypeEnum = typeof ICManufactureBatchLinePartTypeEnum[keyof typeof ICManufactureBatchLinePartTypeEnum];
export const ICManufactureBatchLineTrackingRequiredEnum = {
    None: 'None',
    Complete: 'Complete',
    Incomplete: 'Incomplete'
} as const;

export type ICManufactureBatchLineTrackingRequiredEnum = typeof ICManufactureBatchLineTrackingRequiredEnum[keyof typeof ICManufactureBatchLineTrackingRequiredEnum];


