/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICReceiptBatchLineTracking } from './icreceipt-batch-line-tracking';

/**
 * 
 * @export
 * @interface ICReceiptBatchLine
 */
export interface ICReceiptBatchLine {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'LineType'?: ICReceiptBatchLineLineTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'Description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'TransactionQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'UnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'CostValueExclusive'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'Unit'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'LineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'LotNo'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICReceiptBatchLine
     */
    'LineBreak'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICReceiptBatchLine
     */
    'LineSpace'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'Custom2'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'TrackingRequired'?: ICReceiptBatchLineTrackingRequiredEnum;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICReceiptBatchLine
     */
    'ExpiryDateTracked'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityInStock'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityAllocated'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityAvailable'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityOnBackOrder'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityShipped'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityOnOrder'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityCommitted'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityReturned'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityInProduction'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityInTransit'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityTransferOut'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityTransferIn'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'Weight'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'Volume'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'ExtendedWeight'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'ExtendedVolume'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'MinimumQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'MaximumQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityTheoretical'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'StocktakeVariance'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICReceiptBatchLine
     */
    'QuantityRecReorder'?: number;
    /**
     * 
     * @type {Array<ICReceiptBatchLineTracking>}
     * @memberof ICReceiptBatchLine
     */
    'Tracking'?: Array<ICReceiptBatchLineTracking>;
    /**
     * 
     * @type {string}
     * @memberof ICReceiptBatchLine
     */
    '@odata.etag'?: string;
}

export const ICReceiptBatchLineLineTypeEnum = {
    Product: 'Product',
    Narrative: 'Narrative'
} as const;

export type ICReceiptBatchLineLineTypeEnum = typeof ICReceiptBatchLineLineTypeEnum[keyof typeof ICReceiptBatchLineLineTypeEnum];
export const ICReceiptBatchLineTrackingRequiredEnum = {
    None: 'None',
    Complete: 'Complete',
    Incomplete: 'Incomplete'
} as const;

export type ICReceiptBatchLineTrackingRequiredEnum = typeof ICReceiptBatchLineTrackingRequiredEnum[keyof typeof ICReceiptBatchLineTrackingRequiredEnum];


