/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ICStorePerson
 */
export interface ICStorePerson {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof ICStorePerson
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'StorePersonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'StorePersonName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'Role'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'PhoneNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'PhoneNo3'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'PhoneNo2'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'EmailAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'Comment'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICStorePerson
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICStorePerson
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICStorePerson
     */
    '@odata.etag'?: string;
}

