/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ICTransferList
 */
export interface ICTransferList {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof ICTransferList
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'Comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransferList
     */
    'DocumentID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'DocumentClass'?: ICTransferListDocumentClassEnum;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'DocumentDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'PostStatus'?: ICTransferListPostStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'SourceLocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'PeriodName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'TransitLocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'ReceiptStatus'?: ICTransferListReceiptStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'DestinationLocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'DestinationPeriodName'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'ReceiptDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'DocumentType'?: ICTransferListDocumentTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ICTransferList
     */
    'HasLinks'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICTransferList
     */
    'HasMemos'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ICTransferList
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferList
     */
    'ReceiptPeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'SourceStorePersonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'DestinationStorePersonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransferList
     */
    'TotalWeight'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferList
     */
    'TotalVolume'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransferList
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferList
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferList
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    'ReferenceAlpha'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferList
     */
    '@odata.etag'?: string;
}

export const ICTransferListDocumentClassEnum = {
    Transfer: 'Transfer'
} as const;

export type ICTransferListDocumentClassEnum = typeof ICTransferListDocumentClassEnum[keyof typeof ICTransferListDocumentClassEnum];
export const ICTransferListPostStatusEnum = {
    Unposted: 'Unposted',
    Open: 'Open',
    Posted: 'Posted',
    Deleted: 'Deleted'
} as const;

export type ICTransferListPostStatusEnum = typeof ICTransferListPostStatusEnum[keyof typeof ICTransferListPostStatusEnum];
export const ICTransferListReceiptStatusEnum = {
    Unposted: 'Unposted',
    Open: 'Open',
    Posted: 'Posted',
    Deleted: 'Deleted'
} as const;

export type ICTransferListReceiptStatusEnum = typeof ICTransferListReceiptStatusEnum[keyof typeof ICTransferListReceiptStatusEnum];
export const ICTransferListDocumentTypeEnum = {
    Normal: 'Normal',
    Historic: 'Historic'
} as const;

export type ICTransferListDocumentTypeEnum = typeof ICTransferListDocumentTypeEnum[keyof typeof ICTransferListDocumentTypeEnum];


