/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICTransferLineInwardsTracking } from './ictransfer-line-inwards-tracking';
// May contain unused imports in some cases
// @ts-ignore
import { ICTransferLineTracking } from './ictransfer-line-tracking';

/**
 * 
 * @export
 * @interface ICTransferLine
 */
export interface ICTransferLine {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'LineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'LineType'?: ICTransferLineLineTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'AlternateCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'Description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'QuantityDispatched'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'QuantityReceipted'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'SourceBinCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'DestinationBinCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'Weight'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'Unit'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'QuantityAdjusted'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'Volume'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'SourceQuantityInStock'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'SourceQuantityAvailable'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'DestQuantityInStock'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'DestQuantityAvailable'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'UnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'CostValueExclusive'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'Custom2'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'ExtendedWeight'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransferLine
     */
    'ExtendedVolume'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'BarCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICTransferLine
     */
    'LineBreak'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ICTransferLine
     */
    'LineSpace'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'LotNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'TrackingRequired'?: ICTransferLineTrackingRequiredEnum;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'InwardsTrackingRequired'?: ICTransferLineInwardsTrackingRequiredEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ICTransferLine
     */
    'ExpiryDateTracked'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    'SerialTracked'?: ICTransferLineSerialTrackedEnum;
    /**
     * 
     * @type {boolean}
     * @memberof ICTransferLine
     */
    'LotTracked'?: boolean;
    /**
     * 
     * @type {Array<ICTransferLineTracking>}
     * @memberof ICTransferLine
     */
    'Tracking'?: Array<ICTransferLineTracking>;
    /**
     * 
     * @type {Array<ICTransferLineInwardsTracking>}
     * @memberof ICTransferLine
     */
    'InwardsTracking'?: Array<ICTransferLineInwardsTracking>;
    /**
     * 
     * @type {string}
     * @memberof ICTransferLine
     */
    '@odata.etag'?: string;
}

export const ICTransferLineLineTypeEnum = {
    Product: 'Product',
    Narrative: 'Narrative'
} as const;

export type ICTransferLineLineTypeEnum = typeof ICTransferLineLineTypeEnum[keyof typeof ICTransferLineLineTypeEnum];
export const ICTransferLineTrackingRequiredEnum = {
    None: 'None',
    Complete: 'Complete',
    Incomplete: 'Incomplete'
} as const;

export type ICTransferLineTrackingRequiredEnum = typeof ICTransferLineTrackingRequiredEnum[keyof typeof ICTransferLineTrackingRequiredEnum];
export const ICTransferLineInwardsTrackingRequiredEnum = {
    None: 'None',
    Complete: 'Complete',
    Incomplete: 'Incomplete'
} as const;

export type ICTransferLineInwardsTrackingRequiredEnum = typeof ICTransferLineInwardsTrackingRequiredEnum[keyof typeof ICTransferLineInwardsTrackingRequiredEnum];
export const ICTransferLineSerialTrackedEnum = {
    None: 'None',
    Sale: 'Sale',
    Purchase: 'Purchase'
} as const;

export type ICTransferLineSerialTrackedEnum = typeof ICTransferLineSerialTrackedEnum[keyof typeof ICTransferLineSerialTrackedEnum];


