/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ICTransactionTransaction
 */
export interface ICTransactionTransaction {
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'TransactionType'?: ICTransactionTransactionTransactionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'StockGroupCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'SourceID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'TransactionQuantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'UOMMultiplier'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'UOMTransactionQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'UnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'CostValueExclusive'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'UnitSellingPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'SalesValueExclusive'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'CostOfSalesExclusive'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ICTransactionTransaction
     */
    'NonDiminishing'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'OrderNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'JobCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'CustomerCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'SourceLineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'PriceCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'GstCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'SellPriceBasis'?: ICTransactionTransactionSellPriceBasisEnum;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICTransactionTransaction
     */
    'TransferredToGL'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'ParentID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'SourceType'?: ICTransactionTransactionSourceTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'TransferredValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'GLAccountCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ICTransactionTransaction
     */
    'GLAccountOverridden'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof ICTransactionTransaction
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'ReferenceAlpha'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    'OrderNoAlpha'?: string;
    /**
     * 
     * @type {string}
     * @memberof ICTransactionTransaction
     */
    '@odata.etag'?: string;
}

export const ICTransactionTransactionTransactionTypeEnum = {
    Issue: 'Issue',
    Credit: 'Credit',
    Receipt: 'Receipt',
    Adjustment: 'Adjustment',
    Transfer: 'Transfer',
    Usage: 'Usage',
    Manufacture: 'Manufacture'
} as const;

export type ICTransactionTransactionTransactionTypeEnum = typeof ICTransactionTransactionTransactionTypeEnum[keyof typeof ICTransactionTransactionTransactionTypeEnum];
export const ICTransactionTransactionSellPriceBasisEnum = {
    Inclusive: 'Inclusive',
    Exclusive: 'Exclusive'
} as const;

export type ICTransactionTransactionSellPriceBasisEnum = typeof ICTransactionTransactionSellPriceBasisEnum[keyof typeof ICTransactionTransactionSellPriceBasisEnum];
export const ICTransactionTransactionSourceTypeEnum = {
    Invoice: 'Invoice',
    Credit: 'Credit',
    Shipment: 'Shipment',
    Transfer: 'Transfer',
    Stocktake: 'Stocktake',
    Job: 'Job',
    Manufacture: 'Manufacture',
    SalesOrder: 'Sales Order',
    PurchaseOrder: 'Purchase Order',
    AdjustmentBatch: 'Adjustment Batch',
    WriteOff: 'Write Off',
    ReceiptBatch: 'Receipt Batch',
    BinMovement: 'Bin Movement',
    BinCount: 'Bin Count'
} as const;

export type ICTransactionTransactionSourceTypeEnum = typeof ICTransactionTransactionSourceTypeEnum[keyof typeof ICTransactionTransactionSourceTypeEnum];


