/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface JCBatchList
 */
export interface JCBatchList {
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'JobCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'JobName'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'CustomerCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'JobGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'JobType'?: JCBatchListJobTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'JobStatus'?: JCBatchListJobStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof JCBatchList
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactName'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'CustomerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'DateEntered'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'DateRequired'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'DateCompleted'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'PercentageComplete'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SiteAddress1'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SiteAddress2'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SiteAddress3'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SiteAddress4'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SiteCountryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SitePostCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SellCurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'RateType'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'DateValued'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'ExchangeRate'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JCBatchList
     */
    'FixedRate'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'EstimatedCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'EstimatedSell'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'EstimatedSellBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'QuotedSell'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'QuotedSellBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'ActualsCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'ActualsSell'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'ActualsSellBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'PendingActualsCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'PendingActualsSell'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'PendingActualsSellBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'InvoicedCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'InvoicedAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'InvoicedAmountBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'PendingInvoicedCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'PendingInvoicedSell'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'PendingInvoicedSellBs'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'OrderNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'PriceCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SalesPersonCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'DiscountScheduleCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'Category2'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JCBatchList
     */
    'NonWIP'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'GLClosingWorkInProgressAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'GLWorkInProgressAccountCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'PeriodCompleteForWIP'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'DrawingNo'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'Quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'RelatedJobCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'ContactID'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof JCBatchList
     */
    'ContactEmail'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SiteAddressCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'DefaultLocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactCreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactCreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactCreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactCustomerCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactRole'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactComment'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactCategory1'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactCategory2'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactCustom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactCustom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactTitle'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactFirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactMiddleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactSuffix'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactPhoneNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactPhoneNo2'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactPhoneNo3'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactEmailAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactFirstNameLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactLastNameFirstName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof JCBatchList
     */
    'ContactIsPrimary'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof JCBatchList
     */
    'ContactInactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'ContactLineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'ContactRecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'ContactFullName'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'LastHistoryPeriod'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'SiteAddress5'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'SiteLatitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'SiteLongitude'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'TimeRequired'?: string;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'JobPersonCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'QuotedCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'EditRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'WorkInProgressRecovered'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'WorkInProgressCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'PeriodTransferToGL'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'TransferredToGL'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'PrintStatus'?: JCBatchListPrintStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    'OrderNoAlpha'?: string;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'ExchangeRateRaw'?: number;
    /**
     * 
     * @type {number}
     * @memberof JCBatchList
     */
    'WorkInProgress'?: number;
    /**
     * 
     * @type {string}
     * @memberof JCBatchList
     */
    '@odata.etag'?: string;
}

export const JCBatchListJobTypeEnum = {
    Normal: 'Normal',
    Standard: 'Standard',
    Quote: 'Quote'
} as const;

export type JCBatchListJobTypeEnum = typeof JCBatchListJobTypeEnum[keyof typeof JCBatchListJobTypeEnum];
export const JCBatchListJobStatusEnum = {
    Hold: 'Hold',
    Active: 'Active',
    Complete: 'Complete',
    Deleted: 'Deleted'
} as const;

export type JCBatchListJobStatusEnum = typeof JCBatchListJobStatusEnum[keyof typeof JCBatchListJobStatusEnum];
export const JCBatchListPrintStatusEnum = {
    Unprinted: 'Unprinted',
    Quoted: 'Quoted',
    Printed: 'Printed'
} as const;

export type JCBatchListPrintStatusEnum = typeof JCBatchListPrintStatusEnum[keyof typeof JCBatchListPrintStatusEnum];


