/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OEOrderShip
 */
export interface OEOrderShip {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof OEOrderShip
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof OEOrderShip
     */
    'LineID'?: number;
    /**
     * 
     * @type {number}
     * @memberof OEOrderShip
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof OEOrderShip
     */
    'ShipperCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof OEOrderShip
     */
    'ShipperName'?: string;
    /**
     * 
     * @type {string}
     * @memberof OEOrderShip
     */
    'Reference'?: string;
    /**
     * 
     * @type {number}
     * @memberof OEOrderShip
     */
    'Quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof OEOrderShip
     */
    'TrackingAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof OEOrderShip
     */
    'WebAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof OEOrderShip
     */
    'EmailAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof OEOrderShip
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof OEOrderShip
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof OEOrderShip
     */
    '@odata.etag'?: string;
}

