/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICBinMovement } from './icbin-movement';

/**
 * 
 * @export
 * @interface PagedICBinMovement
 */
export interface PagedICBinMovement {
    /**
     * 
     * @type {string}
     * @memberof PagedICBinMovement
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedICBinMovement
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<ICBinMovement>}
     * @memberof PagedICBinMovement
     */
    'value'?: Array<ICBinMovement>;
}

