/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLEAPCTWORD } from './tableapctword';

/**
 * 
 * @export
 * @interface PagedTABLEAPCTWORD
 */
export interface PagedTABLEAPCTWORD {
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEAPCTWORD
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEAPCTWORD
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLEAPCTWORD>}
     * @memberof PagedTABLEAPCTWORD
     */
    'value'?: Array<TABLEAPCTWORD>;
}

