/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { JCCategory1 } from './jccategory1';

/**
 * 
 * @export
 * @interface PagedJCCategory1
 */
export interface PagedJCCategory1 {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {string}
     * @memberof PagedJCCategory1
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedJCCategory1
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<JCCategory1>}
     * @memberof PagedJCCategory1
     */
    'value'?: Array<JCCategory1>;
}

