/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLECBCAT2 } from './tablecbcat2';

/**
 * 
 * @export
 * @interface PagedTABLECBCAT2
 */
export interface PagedTABLECBCAT2 {
    [key: string]: any;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECBCAT2
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECBCAT2
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLECBCAT2>}
     * @memberof PagedTABLECBCAT2
     */
    'value'?: Array<TABLECBCAT2>;
}

