/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICReceiptBatch } from './icreceipt-batch';

/**
 * 
 * @export
 * @interface PagedICReceiptBatch
 */
export interface PagedICReceiptBatch {
    /**
     * 
     * @type {string}
     * @memberof PagedICReceiptBatch
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedICReceiptBatch
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<ICReceiptBatch>}
     * @memberof PagedICReceiptBatch
     */
    'value'?: Array<ICReceiptBatch>;
}

