/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CBAnalysisBudget } from './cbanalysis-budget';

/**
 * 
 * @export
 * @interface PagedCBAnalysisBudget
 */
export interface PagedCBAnalysisBudget {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {string}
     * @memberof PagedCBAnalysisBudget
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedCBAnalysisBudget
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<CBAnalysisBudget>}
     * @memberof PagedCBAnalysisBudget
     */
    'value'?: Array<CBAnalysisBudget>;
}

