/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLEFACAT2 } from './tablefacat2';

/**
 * 
 * @export
 * @interface PagedTABLEFACAT2
 */
export interface PagedTABLEFACAT2 {
    [key: string]: any;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEFACAT2
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEFACAT2
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLEFACAT2>}
     * @memberof PagedTABLEFACAT2
     */
    'value'?: Array<TABLEFACAT2>;
}

