/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLEGLTRAN } from './tablegltran';

/**
 * 
 * @export
 * @interface PagedTABLEGLTRAN
 */
export interface PagedTABLEGLTRAN {
    [key: string]: any;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEGLTRAN
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEGLTRAN
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLEGLTRAN>}
     * @memberof PagedTABLEGLTRAN
     */
    'value'?: Array<TABLEGLTRAN>;
}

