/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FACategory1 } from './facategory1';

/**
 * 
 * @export
 * @interface PagedFACategory1
 */
export interface PagedFACategory1 {
    [key: string]: any;
    /**
     * 
     * @type {string}
     * @memberof PagedFACategory1
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedFACategory1
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<FACategory1>}
     * @memberof PagedFACategory1
     */
    'value'?: Array<FACategory1>;
}

