/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLEAPMEMOLN } from './tableapmemoln';

/**
 * 
 * @export
 * @interface PagedTABLEAPMEMOLN
 */
export interface PagedTABLEAPMEMOLN {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEAPMEMOLN
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEAPMEMOLN
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLEAPMEMOLN>}
     * @memberof PagedTABLEAPMEMOLN
     */
    'value'?: Array<TABLEAPMEMOLN>;
}

