/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLEJCCAT2 } from './tablejccat2';

/**
 * 
 * @export
 * @interface PagedTABLEJCCAT2
 */
export interface PagedTABLEJCCAT2 {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEJCCAT2
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLEJCCAT2
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLEJCCAT2>}
     * @memberof PagedTABLEJCCAT2
     */
    'value'?: Array<TABLEJCCAT2>;
}

