/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ICTransactionList } from './ictransaction-list';

/**
 * 
 * @export
 * @interface PagedICTransactionList
 */
export interface PagedICTransactionList {
    /**
     * 
     * @type {string}
     * @memberof PagedICTransactionList
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedICTransactionList
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<ICTransactionList>}
     * @memberof PagedICTransactionList
     */
    'value'?: Array<ICTransactionList>;
}

