/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLECOPRTLOG } from './tablecoprtlog';

/**
 * 
 * @export
 * @interface PagedTABLECOPRTLOG
 */
export interface PagedTABLECOPRTLOG {
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECOPRTLOG
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECOPRTLOG
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLECOPRTLOG>}
     * @memberof PagedTABLECOPRTLOG
     */
    'value'?: Array<TABLECOPRTLOG>;
}

