/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { TABLECOALIAS } from './tablecoalias';

/**
 * 
 * @export
 * @interface PagedTABLECOALIAS
 */
export interface PagedTABLECOALIAS {
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECOALIAS
     */
    '@odata.deltaLink'?: string;
    /**
     * 
     * @type {string}
     * @memberof PagedTABLECOALIAS
     */
    '@odata.context'?: string;
    /**
     * 
     * @type {Array<TABLECOALIAS>}
     * @memberof PagedTABLECOALIAS
     */
    'value'?: Array<TABLECOALIAS>;
}

