/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface POMemoMemo
 */
export interface POMemoMemo {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {string}
     * @memberof POMemoMemo
     */
    'Text'?: string;
    /**
     * 
     * @type {string}
     * @memberof POMemoMemo
     */
    '@odata.etag'?: string;
}

