/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SPRuleBreak
 */
export interface SPRuleBreak {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof SPRuleBreak
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof SPRuleBreak
     */
    'RuleID'?: number;
    /**
     * 
     * @type {number}
     * @memberof SPRuleBreak
     */
    'MinimumQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof SPRuleBreak
     */
    'Amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof SPRuleBreak
     */
    'Percentage'?: number;
    /**
     * 
     * @type {string}
     * @memberof SPRuleBreak
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleBreak
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof SPRuleBreak
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof SPRuleBreak
     */
    '@odata.etag'?: string;
}

