/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SPRuleListForm
 */
export interface SPRuleListForm {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof SPRuleListForm
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof SPRuleListForm
     */
    'RuleID'?: number;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'Who1Type'?: SPRuleListFormWho1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'Who1Code'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'What1Type'?: SPRuleListFormWhat1TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'What1Code'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'Who1Desc'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'What1Desc'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SPRuleListForm
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'RuleType'?: SPRuleListFormRuleTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'BaseCost'?: SPRuleListFormBaseCostEnum;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'BaseSell'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof SPRuleListForm
     */
    'BypassMinimumMargin'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'StartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'EndDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof SPRuleListForm
     */
    'Priority'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SPRuleListForm
     */
    'UOMQuantity'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SPRuleListForm
     */
    'HasQuantityBreaks'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof SPRuleListForm
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'Who1Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'Who2Type'?: SPRuleListFormWho2TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'Who2Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'What1Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'What2Type'?: SPRuleListFormWhat2TypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'What2Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    'Where1Name'?: string;
    /**
     * 
     * @type {string}
     * @memberof SPRuleListForm
     */
    '@odata.etag'?: string;
}

export const SPRuleListFormWho1TypeEnum = {
    Customer: 'Customer',
    CustomerGroup: 'Customer Group',
    SalesArea: 'Sales Area',
    SalesPerson: 'Sales Person',
    PriceCode: 'Price Code',
    Discount: 'Discount',
    DeliveryAddress: 'Delivery Address',
    ArCategory1: 'AR Category 1',
    ArCategory2: 'AR Category 2',
    InCategory1: 'IN Category 1',
    InCategory2: 'IN Category 2',
    Job: 'Job',
    JobGroup: 'Job Group',
    JcCategory1: 'JC Category 1',
    JcCategory2: 'JC Category 2',
    None: 'None'
} as const;

export type SPRuleListFormWho1TypeEnum = typeof SPRuleListFormWho1TypeEnum[keyof typeof SPRuleListFormWho1TypeEnum];
export const SPRuleListFormWhat1TypeEnum = {
    Product: 'Product',
    StockGroup: 'Stock Group',
    SalesGroup: 'Sales Group',
    Creditor: 'Creditor',
    Discount: 'Discount',
    IcCategory1: 'IC Category 1',
    IcCategory2: 'IC Category 2',
    None: 'None'
} as const;

export type SPRuleListFormWhat1TypeEnum = typeof SPRuleListFormWhat1TypeEnum[keyof typeof SPRuleListFormWhat1TypeEnum];
export const SPRuleListFormRuleTypeEnum = {
    Fixed: 'Fixed',
    CostRelative: 'Cost Relative',
    SellRelative: 'Sell Relative'
} as const;

export type SPRuleListFormRuleTypeEnum = typeof SPRuleListFormRuleTypeEnum[keyof typeof SPRuleListFormRuleTypeEnum];
export const SPRuleListFormBaseCostEnum = {
    Valuation: 'Valuation',
    Standard: 'Standard',
    Latest: 'Latest',
    Average: 'Average'
} as const;

export type SPRuleListFormBaseCostEnum = typeof SPRuleListFormBaseCostEnum[keyof typeof SPRuleListFormBaseCostEnum];
export const SPRuleListFormWho2TypeEnum = {
    Customer: 'Customer',
    CustomerGroup: 'Customer Group',
    SalesArea: 'Sales Area',
    SalesPerson: 'Sales Person',
    PriceCode: 'Price Code',
    Discount: 'Discount',
    DeliveryAddress: 'Delivery Address',
    ArCategory1: 'AR Category 1',
    ArCategory2: 'AR Category 2',
    InCategory1: 'IN Category 1',
    InCategory2: 'IN Category 2',
    Job: 'Job',
    JobGroup: 'Job Group',
    JcCategory1: 'JC Category 1',
    JcCategory2: 'JC Category 2',
    None: 'None'
} as const;

export type SPRuleListFormWho2TypeEnum = typeof SPRuleListFormWho2TypeEnum[keyof typeof SPRuleListFormWho2TypeEnum];
export const SPRuleListFormWhat2TypeEnum = {
    Product: 'Product',
    StockGroup: 'Stock Group',
    SalesGroup: 'Sales Group',
    Creditor: 'Creditor',
    Discount: 'Discount',
    IcCategory1: 'IC Category 1',
    IcCategory2: 'IC Category 2',
    None: 'None'
} as const;

export type SPRuleListFormWhat2TypeEnum = typeof SPRuleListFormWhat2TypeEnum[keyof typeof SPRuleListFormWhat2TypeEnum];


