/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICADHEAD
 */
export interface TABLEICADHEAD {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEICADHEAD
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICADHEAD
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICADHEAD
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'Details'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'StorePersonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'PrintStatus'?: TABLEICADHEADPrintStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'PostStatus'?: TABLEICADHEADPostStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEICADHEAD
     */
    'TotalWeight'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICADHEAD
     */
    'TotalVolume'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICADHEAD
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICADHEAD
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICADHEAD
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICADHEAD
     */
    'ReferenceAlpha'?: string;
}

export const TABLEICADHEADPrintStatusEnum = {
    Unprinted: 'Unprinted',
    Printed: 'Printed'
} as const;

export type TABLEICADHEADPrintStatusEnum = typeof TABLEICADHEADPrintStatusEnum[keyof typeof TABLEICADHEADPrintStatusEnum];
export const TABLEICADHEADPostStatusEnum = {
    Unposted: 'Unposted',
    Open: 'Open',
    Posted: 'Posted',
    Deleted: 'Deleted'
} as const;

export type TABLEICADHEADPostStatusEnum = typeof TABLEICADHEADPostStatusEnum[keyof typeof TABLEICADHEADPostStatusEnum];


