/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICPEND
 */
export interface TABLEICPEND {
    /**
     * 
     * @type {number}
     * @memberof TABLEICPEND
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPEND
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPEND
     */
    'SourceType'?: TABLEICPENDSourceTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPEND
     */
    'SourceDocumentID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPEND
     */
    'SourceLineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPEND
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPEND
     */
    'Class'?: TABLEICPENDClassEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPEND
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPEND
     */
    'UOMMultiplier'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPEND
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPEND
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPEND
     */
    'UOMQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPEND
     */
    'Quantity'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPEND
     */
    'Contra'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPEND
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPEND
     */
    'PeriodNo'?: number;
}

export const TABLEICPENDSourceTypeEnum = {
    Invoice: 'Invoice',
    Credit: 'Credit',
    Shipment: 'Shipment',
    Transfer: 'Transfer',
    Stocktake: 'Stocktake',
    Job: 'Job',
    Manufacture: 'Manufacture',
    SalesOrder: 'Sales Order',
    PurchaseOrder: 'Purchase Order',
    AdjustmentBatch: 'Adjustment Batch',
    WriteOff: 'Write Off',
    ReceiptBatch: 'Receipt Batch',
    BinMovement: 'Bin Movement',
    BinCount: 'Bin Count'
} as const;

export type TABLEICPENDSourceTypeEnum = typeof TABLEICPENDSourceTypeEnum[keyof typeof TABLEICPENDSourceTypeEnum];
export const TABLEICPENDClassEnum = {
    Allocation: 'Allocation',
    BackOrder: 'Back Order',
    Order: 'Order',
    TransferIn: 'Transfer In',
    TransferOut: 'Transfer Out',
    Shipped: 'Shipped',
    Commitment: 'Commitment',
    InProduction: 'In Production',
    Returned: 'Returned',
    Variation: 'Variation',
    WriteOff: 'Write Off'
} as const;

export type TABLEICPENDClassEnum = typeof TABLEICPENDClassEnum[keyof typeof TABLEICPENDClassEnum];


