/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECOTRACK
 */
export interface TABLECOTRACK {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLECOTRACK
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOTRACK
     */
    'TableName'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECOTRACK
     */
    'HeatLimit'?: number;
}

