/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECBRUDISS
 */
export interface TABLECBRUDISS {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLECBRUDISS
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBRUDISS
     */
    'RuleID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECBRUDISS
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBRUDISS
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBRUDISS
     */
    'GLAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBRUDISS
     */
    'Narration'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBRUDISS
     */
    'AnalysisCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBRUDISS
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBRUDISS
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECBRUDISS
     */
    'ExclusiveAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECBRUDISS
     */
    'GstCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECBRUDISS
     */
    'GstAmount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBRUDISS
     */
    'Percentage'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBRUDISS
     */
    'LineNo'?: number;
}

