/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICTRKDTL
 */
export interface TABLEICTRKDTL {
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'DetailID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICTRKDTL
     */
    'Pending'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICTRKDTL
     */
    'TentativeSerialNo'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICTRKDTL
     */
    'TentativeLotNo'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'LotNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'BinCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'LotDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'ExpiryDate'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICTRKDTL
     */
    'FixedLot'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'SourceType'?: TABLEICTRKDTLSourceTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'SourceID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'SourceLineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'Class'?: TABLEICTRKDTLClassEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'LineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'Quantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'UOMQuantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICTRKDTL
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'UOMMultiplier'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICTRKDTL
     */
    'Contra'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICTRKDTL
     */
    'PeriodNo'?: number;
}

export const TABLEICTRKDTLSourceTypeEnum = {
    Invoice: 'Invoice',
    Credit: 'Credit',
    Shipment: 'Shipment',
    Transfer: 'Transfer',
    Stocktake: 'Stocktake',
    Job: 'Job',
    Manufacture: 'Manufacture',
    SalesOrder: 'Sales Order',
    PurchaseOrder: 'Purchase Order',
    AdjustmentBatch: 'Adjustment Batch',
    WriteOff: 'Write Off',
    ReceiptBatch: 'Receipt Batch',
    BinMovement: 'Bin Movement',
    BinCount: 'Bin Count'
} as const;

export type TABLEICTRKDTLSourceTypeEnum = typeof TABLEICTRKDTLSourceTypeEnum[keyof typeof TABLEICTRKDTLSourceTypeEnum];
export const TABLEICTRKDTLClassEnum = {
    Allocation: 'Allocation',
    TransferOut: 'Transfer Out',
    Variation: 'Variation',
    TransferIn: 'Transfer In',
    Shipped: 'Shipped',
    Commitment: 'Commitment',
    Returned: 'Returned',
    WriteOff: 'Write Off',
    InProduction: 'In Production'
} as const;

export type TABLEICTRKDTLClassEnum = typeof TABLEICTRKDTLClassEnum[keyof typeof TABLEICTRKDTLClassEnum];


