/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEGLSUB
 */
export interface TABLEGLSUB {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLSUB
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLSUB
     */
    'CompanyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLSUB
     */
    'CompanyName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGLSUB
     */
    'ImportSource'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGLSUB
     */
    'ImportDestination'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLSUB
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLSUB
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGLSUB
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLSUB
     */
    'RecordRevision'?: number;
}

