/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEGLMEMOLN
 */
export interface TABLEGLMEMOLN {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLMEMOLN
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLMEMOLN
     */
    'MemoID'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGLMEMOLN
     */
    'LineBreak'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGLMEMOLN
     */
    'LineSpace'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLMEMOLN
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLMEMOLN
     */
    'LineText'?: string;
}

