/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECOCNTRY
 */
export interface TABLECOCNTRY {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCNTRY
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCNTRY
     */
    'CountryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCNTRY
     */
    'CountryName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCNTRY
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCNTRY
     */
    'RecordRevision'?: number;
}

