/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEGSRTSM
 */
export interface TABLEGSRTSM {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'ReturnID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTSM
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesNotReported'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesTaxable'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesGstIncluded'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesGstIncludedBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesGstAdjustments'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesGstAdjustmentsBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesInputTaxed'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesGstFree'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesExports'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesZeroRated'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'SalesGstClearing'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesNotReported'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesTaxable'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesGstIncluded'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesGstIncludedBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesGstAdjustments'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesGstAdjustmentsBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesCapital'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesOther'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesInputTaxed'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesGstFree'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesZeroRated'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'PurchasesGstClearing'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransSalesTaxable'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransSalesGstIncluded'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransSalesGstAdjustments'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransSalesZeroRated'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransSalesGstClearing'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransPurchasesTaxable'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransPurchasesGstIncluded'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransPurchasesGstAdjustments'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransPurchasesGstDiscount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransPurchasesZeroRated'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'TransPurchasesGstClearing'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'GstPayable'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'GstPayableBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'ProvisionalRatio'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'ProvisionalLastMonthBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'ProvisionalOtherBranchBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'ProvisionalAssetAdjustBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'ProvisionalPayableBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'ProvisionalVoluntaryBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTSM
     */
    'ProvisionalGstRefundBs'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTSM
     */
    'GatewayID'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTSM
     */
    'SubmissionKey'?: string;
}

