/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECOCONTCT
 */
export interface TABLECOCONTCT {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCONTCT
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCONTCT
     */
    'ContactID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'Role'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'Title'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'FirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'MiddleName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'LastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'Suffix'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'PhoneNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'PhoneNo2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'PhoneNo3'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'CompanyName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'EmailAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'FirstNameLastName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'LastNameFirstName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'TableName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'PartyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCONTCT
     */
    'PartyContactID'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLECOCONTCT
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCONTCT
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCONTCT
     */
    'FullName'?: string;
}

