/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEAPWORD
 */
export interface TABLEAPWORD {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEAPWORD
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPWORD
     */
    'Word'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPWORD
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEAPWORD
     */
    'Count'?: number;
}

