/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICBIN
 */
export interface TABLEICBIN {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBIN
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBIN
     */
    'BinID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBIN
     */
    'BinCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBIN
     */
    'BinName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBIN
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICBIN
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBIN
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBIN
     */
    'Custom2'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBIN
     */
    'PickingPriority'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBIN
     */
    'PickingSequence'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBIN
     */
    'DateOfLastCount'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBIN
     */
    'ActiveBinCountID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBIN
     */
    'RecordRevision'?: number;
}

