/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICPARTHD
 */
export interface TABLEICPARTHD {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPARTHD
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'SerialNoPrefix'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'SerialNoSuffix'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPARTHD
     */
    'AutomaticSubcomponent'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'ExpiryUnit'?: TABLEICPARTHDExpiryUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPARTHD
     */
    'ExpiryCount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPARTHD
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPARTHD
     */
    'SerialNoCounter'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPARTHD
     */
    'RecordRevision'?: number;
}

export const TABLEICPARTHDExpiryUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months',
    Years: 'Years'
} as const;

export type TABLEICPARTHDExpiryUnitEnum = typeof TABLEICPARTHDExpiryUnitEnum[keyof typeof TABLEICPARTHDExpiryUnitEnum];


