/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECOCUSTTB
 */
export interface TABLECOCUSTTB {
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTTB
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTTB
     */
    'CustomisationID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCUSTTB
     */
    'ToolbarName'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTTB
     */
    'BindID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCUSTTB
     */
    'UserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCUSTTB
     */
    'ButtonName'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTTB
     */
    'ButtonOrder'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOCUSTTB
     */
    'VisibilityType'?: TABLECOCUSTTBVisibilityTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTTB
     */
    'ImageIndex'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECOCUSTTB
     */
    'RecordRevision'?: number;
}

export const TABLECOCUSTTBVisibilityTypeEnum = {
    ToolbarAndMenu: 'Toolbar and Menu',
    MenuOnly: 'Menu Only',
    NotVisible: 'Not Visible'
} as const;

export type TABLECOCUSTTBVisibilityTypeEnum = typeof TABLECOCUSTTBVisibilityTypeEnum[keyof typeof TABLECOCUSTTBVisibilityTypeEnum];


