/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEJCPEND
 */
export interface TABLEJCPEND {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'JobCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'Class'?: TABLEJCPENDClassEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'TransactionType'?: TABLEJCPENDTransactionTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'SourceDocumentID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'SourceLineID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'SellCurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'SalesGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'CostCentreCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'ComponentCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'TransactionQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'ExtendedSell'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'ExtendedSellBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'ExtendedCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'Description'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'DiscountPercentage'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'ExchangeRate'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEJCPEND
     */
    'FullyInvoiced'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'GLAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'LotNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'RateType'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'Narration'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'UOMMultiplier'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'Unit'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'UOMUnitSellPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'UnitSellPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'UOMUnitSellPriceBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'UnitSellPriceBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'UOMUnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'UnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'OrderNo'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'ExchangeRateRaw'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCPEND
     */
    'OrderNoAlpha'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'MarginPercentage'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCPEND
     */
    'MarkupPercentage'?: number;
}

export const TABLEJCPENDClassEnum = {
    Actual: 'Actual',
    Invoiced: 'Invoiced'
} as const;

export type TABLEJCPENDClassEnum = typeof TABLEJCPENDClassEnum[keyof typeof TABLEJCPENDClassEnum];
export const TABLEJCPENDTransactionTypeEnum = {
    Time: 'Time',
    Material: 'Material',
    Disbursement: 'Disbursement',
    Narrative: 'Narrative'
} as const;

export type TABLEJCPENDTransactionTypeEnum = typeof TABLEJCPENDTransactionTypeEnum[keyof typeof TABLEJCPENDTransactionTypeEnum];


