/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICBAR
 */
export interface TABLEICBAR {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBAR
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBAR
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBAR
     */
    'BarCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBAR
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBAR
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBAR
     */
    'CustomerCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBAR
     */
    'Comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBAR
     */
    'RecordRevision'?: number;
}

