/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEGSMEMO
 */
export interface TABLEGSMEMO {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSMEMO
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSMEMO
     */
    'MemoID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'AccountFile'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'RegimeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'Custom2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'MemoDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'MemoTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'Subject'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'MemoType'?: TABLEGSMEMOMemoTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'TargetUserCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGSMEMO
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'ActionOnDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'ActionOnTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSMEMO
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSMEMO
     */
    'RecordRevision'?: number;
}

export const TABLEGSMEMOMemoTypeEnum = {
    Memo: 'Memo',
    Alarm: 'Alarm',
    Reminder: 'Reminder'
} as const;

export type TABLEGSMEMOMemoTypeEnum = typeof TABLEGSMEMOMemoTypeEnum[keyof typeof TABLEGSMEMOMemoTypeEnum];


