/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICPROD
 */
export interface TABLEICPROD {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SellCurrencyCode1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SellCurrencyCode2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SellCurrencyCode3'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SellCurrencyCode4'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SellCurrencyCode5'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SellCurrencyCode6'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SellCurrencyCode7'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SellCurrencyCode8'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SellCurrencyCode9'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'LastHistoryPeriod'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'GstCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'HasRegimeOverrides'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'NonDiminishing'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'ManuallyCosted'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'BackOrder'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'Discontinued'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'AlternateCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'BarCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'Unit'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'BaseUOMCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SaleUOMCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'PurchaseUOMCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'ImageType'?: TABLEICPRODImageTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'ImagePath'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'Details'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'Description'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'Volume'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'Weight'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'DiscountScheduleCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'CreditorCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'LeadTime'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'Duty'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'StockGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SalesGroupCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'CommissionPercentage'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'ExpenseCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'JCTransactionType'?: TABLEICPRODJCTransactionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'CostCentreCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'ComponentCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'StandardCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarkupPercent1'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarkupPercent2'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarkupPercent3'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarkupPercent4'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarkupPercent5'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarkupPercent6'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarkupPercent7'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarkupPercent8'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarkupPercent9'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MinimumQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MaximumQuantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'ComponentMode'?: TABLEICPRODComponentModeEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'SerialTracked'?: TABLEICPRODSerialTrackedEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SerialNoLength'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'LotTracked'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'LotNoLength'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'ExpiryDateTracked'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'SupplySingleLot'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'GenerateLotNos'?: TABLEICPRODGenerateLotNosEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'MinimumExpiryUnit'?: TABLEICPRODMinimumExpiryUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MinimumExpiryCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'RetainYearsTracking'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'HasParts'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SellingPrice1'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SellingPrice2'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SellingPrice3'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SellingPrice4'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SellingPrice5'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SellingPrice6'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SellingPrice7'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SellingPrice8'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SellingPrice9'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'LatestCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'AverageCost'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'EditRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'OpeningStockYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'OpeningStockPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'AdjustmentsPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'AdjustmentsYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'StocktakeVariance'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'DateOfLastStocktake'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'RevaluationPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'RevaluationYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'ManufacturedPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'ManufacturedYearToDate'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'DateOfLastManufacture'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'ReceiptsPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'ReceiptsYearToDate'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'DateOfLastReceipt'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'NonDiminishingPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'NonDiminishingYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'UsagePeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'UsageYearToDate'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'DateOfLastUsage'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SalesQuantityPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SalesValuePeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'CostOfSalesPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SalesQuantityYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'SalesValueYearToDate'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICPROD
     */
    'DateOfLastSale'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'CostOfSalesYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'CostValuePeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'CostValueYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityInStock'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityReturned'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityTransferIn'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityTransferOut'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityInProduction'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityCommitted'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityShipped'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityOnOrder'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityOnBackOrder'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityAllocated'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'ClosingPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'ClosingYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarginPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'MarginYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityAvailable'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityTheoretical'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICPROD
     */
    'QuantityRecReorder'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICPROD
     */
    'IsTracked'?: boolean;
}

export const TABLEICPRODImageTypeEnum = {
    File: 'File',
    Web: 'Web'
} as const;

export type TABLEICPRODImageTypeEnum = typeof TABLEICPRODImageTypeEnum[keyof typeof TABLEICPRODImageTypeEnum];
export const TABLEICPRODJCTransactionTypeEnum = {
    Time: 'Time',
    Material: 'Material',
    Disbursement: 'Disbursement',
    Narrative: 'Narrative'
} as const;

export type TABLEICPRODJCTransactionTypeEnum = typeof TABLEICPRODJCTransactionTypeEnum[keyof typeof TABLEICPRODJCTransactionTypeEnum];
export const TABLEICPRODComponentModeEnum = {
    None: 'None',
    AutomaticKitset: 'Automatic Kitset',
    ManualKitset: 'Manual Kitset',
    Manufacture: 'Manufacture'
} as const;

export type TABLEICPRODComponentModeEnum = typeof TABLEICPRODComponentModeEnum[keyof typeof TABLEICPRODComponentModeEnum];
export const TABLEICPRODSerialTrackedEnum = {
    None: 'None',
    Sale: 'Sale',
    Purchase: 'Purchase'
} as const;

export type TABLEICPRODSerialTrackedEnum = typeof TABLEICPRODSerialTrackedEnum[keyof typeof TABLEICPRODSerialTrackedEnum];
export const TABLEICPRODGenerateLotNosEnum = {
    None: 'None',
    ExpiryDate: 'Expiry Date',
    LotDate: 'Lot Date'
} as const;

export type TABLEICPRODGenerateLotNosEnum = typeof TABLEICPRODGenerateLotNosEnum[keyof typeof TABLEICPRODGenerateLotNosEnum];
export const TABLEICPRODMinimumExpiryUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months',
    Years: 'Years'
} as const;

export type TABLEICPRODMinimumExpiryUnitEnum = typeof TABLEICPRODMinimumExpiryUnitEnum[keyof typeof TABLEICPRODMinimumExpiryUnitEnum];


