/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEARGROUP
 */
export interface TABLEARGROUP {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEARGROUP
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'CustomerGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'CustomerGroupName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'DefaultBankAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'DefaultRegimeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'DefaultGSTOverride'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'DefaultPriceCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'GLDebtorAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'GLBankAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'GLDiscountAccountCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARGROUP
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'EASCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'StatementAgingUnit'?: TABLEARGROUPStatementAgingUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEARGROUP
     */
    'StatementAgingCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARGROUP
     */
    'Discount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'DiscountUnit'?: TABLEARGROUPDiscountUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEARGROUP
     */
    'DiscountCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARGROUP
     */
    'DiscountDayOfMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'PaymentUnit'?: TABLEARGROUPPaymentUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEARGROUP
     */
    'PaymentCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARGROUP
     */
    'PaymentDayOfMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARGROUP
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARGROUP
     */
    'RecordRevision'?: number;
}

export const TABLEARGROUPStatementAgingUnitEnum = {
    Period: 'Period',
    Months: 'Months',
    Days: 'Days'
} as const;

export type TABLEARGROUPStatementAgingUnitEnum = typeof TABLEARGROUPStatementAgingUnitEnum[keyof typeof TABLEARGROUPStatementAgingUnitEnum];
export const TABLEARGROUPDiscountUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months'
} as const;

export type TABLEARGROUPDiscountUnitEnum = typeof TABLEARGROUPDiscountUnitEnum[keyof typeof TABLEARGROUPDiscountUnitEnum];
export const TABLEARGROUPPaymentUnitEnum = {
    Period: 'Period',
    Months: 'Months',
    Weeks: 'Weeks',
    Days: 'Days'
} as const;

export type TABLEARGROUPPaymentUnitEnum = typeof TABLEARGROUPPaymentUnitEnum[keyof typeof TABLEARGROUPPaymentUnitEnum];


