/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEGLLINE
 */
export interface TABLEGLLINE {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLLINE
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLLINE
     */
    'LineID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLLINE
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'SourceModule'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLLINE
     */
    'SourceID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLLINE
     */
    'SourceLineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'SourceCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'Narration'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLLINE
     */
    'TransactionAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLLINE
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLLINE
     */
    'ReferenceAlpha'?: string;
}

