/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEGSLINK
 */
export interface TABLEGSLINK {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSLINK
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSLINK
     */
    'LinkID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'AccountFile'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'RegimeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'LinkType'?: TABLEGSLINKLinkTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'FilePath'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSLINK
     */
    'LineNo'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGSLINK
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSLINK
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSLINK
     */
    'RecordRevision'?: number;
}

export const TABLEGSLINKLinkTypeEnum = {
    File: 'File',
    Web: 'Web'
} as const;

export type TABLEGSLINKLinkTypeEnum = typeof TABLEGSLINKLinkTypeEnum[keyof typeof TABLEGSLINKLinkTypeEnum];


