/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECOPHONE
 */
export interface TABLECOPHONE {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLECOPHONE
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPHONE
     */
    'TableName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPHONE
     */
    'PhoneType'?: TABLECOPHONEPhoneTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPHONE
     */
    'PartyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECOPHONE
     */
    'ContactID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPHONE
     */
    'PhoneNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPHONE
     */
    'TransformedNo'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLECOPHONE
     */
    'Inactive'?: boolean;
}

export const TABLECOPHONEPhoneTypeEnum = {
    AccountPhoneNo: 'Account Phone No',
    AccountPhoneNo2: 'Account Phone No 2',
    AccountPhoneNo3: 'Account Phone No 3',
    ContactPhoneNo: 'Contact Phone No',
    ContactPhoneNo2: 'Contact Phone No 2',
    ContactPhoneNo3: 'Contact Phone No 3',
    EmergencyPhoneNo: 'Emergency Phone No',
    EmergencyPhoneNo2: 'Emergency Phone No 2'
} as const;

export type TABLECOPHONEPhoneTypeEnum = typeof TABLECOPHONEPhoneTypeEnum[keyof typeof TABLECOPHONEPhoneTypeEnum];


