/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEFACODE
 */
export interface TABLEFACODE {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEFACODE
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEFACODE
     */
    'DepreciationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEFACODE
     */
    'DepreciationDescription'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEFACODE
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEFACODE
     */
    'RecordRevision'?: number;
}

