/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECOMODULE
 */
export interface TABLECOMODULE {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLECOMODULE
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOMODULE
     */
    'ModuleCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLECOMODULE
     */
    'AbnormalTermination'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLECOMODULE
     */
    'LastRecovered'?: string;
}

