/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICMFHEAD
 */
export interface TABLEICMFHEAD {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'Details'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'TransactionDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'Reference'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'Comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'UOMMultiplier'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'LotNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'ExpiryDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'BinCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'ManufactureID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'StorePersonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'UOMTransactionQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'TransactionQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'UOMUnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'UnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'CostValueExclusive'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'PrintStatus'?: TABLEICMFHEADPrintStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'PostStatus'?: TABLEICMFHEADPostStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'TotalWeight'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'TotalVolume'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFHEAD
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFHEAD
     */
    'ReferenceAlpha'?: string;
}

export const TABLEICMFHEADPrintStatusEnum = {
    Unprinted: 'Unprinted',
    Printed: 'Printed'
} as const;

export type TABLEICMFHEADPrintStatusEnum = typeof TABLEICMFHEADPrintStatusEnum[keyof typeof TABLEICMFHEADPrintStatusEnum];
export const TABLEICMFHEADPostStatusEnum = {
    Unposted: 'Unposted',
    Open: 'Open',
    Posted: 'Posted',
    Deleted: 'Deleted'
} as const;

export type TABLEICMFHEADPostStatusEnum = typeof TABLEICMFHEADPostStatusEnum[keyof typeof TABLEICMFHEADPostStatusEnum];


