/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICBNCTLN
 */
export interface TABLEICBNCTLN {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'LineID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNCTLN
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNCTLN
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNCTLN
     */
    'LotNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNCTLN
     */
    'LotDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNCTLN
     */
    'ExpiryDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'QuantityExpected'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNCTLN
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'UOMMultiplier'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'QuantityCounted'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'UOMQuantityCounted'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICBNCTLN
     */
    'Adjust'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'LineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'TransactionID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNCTLN
     */
    'QuantityVariance'?: number;
}

