/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEGLACTREC
 */
export interface TABLEGLACTREC {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLACTREC
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLACTREC
     */
    'ReconciliationID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLACTREC
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'Details'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'ReconciliationDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLACTREC
     */
    'ReconciliationAmount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLACTREC
     */
    'Status'?: TABLEGLACTRECStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLACTREC
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLACTREC
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLACTREC
     */
    'PeriodNo'?: number;
}

export const TABLEGLACTRECStatusEnum = {
    Open: 'Open',
    Closed: 'Closed',
    Deleted: 'Deleted'
} as const;

export type TABLEGLACTRECStatusEnum = typeof TABLEGLACTRECStatusEnum[keyof typeof TABLEGLACTRECStatusEnum];


