/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEGLCTRL
 */
export interface TABLEGLCTRL {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLCTRL
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLCTRL
     */
    'UserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGLCTRL
     */
    'Name'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLCTRL
     */
    'Type'?: number;
    /**
     * 
     * @type {object}
     * @memberof TABLEGLCTRL
     */
    'Value'?: object;
    /**
     * 
     * @type {number}
     * @memberof TABLEGLCTRL
     */
    'RecordRevision'?: number;
}

