/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEAPGROUP
 */
export interface TABLEAPGROUP {
    /**
     * 
     * @type {number}
     * @memberof TABLEAPGROUP
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'CreditorGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'CreditorGroupName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'DefaultBankAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'DefaultRegimeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'DefaultGSTOverride'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'GLCreditorAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'GLBankAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'GLDiscountAccountCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEAPGROUP
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'DefaultPaymentMethod'?: TABLEAPGROUPDefaultPaymentMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'EASCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEAPGROUP
     */
    'Discount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'DiscountUnit'?: TABLEAPGROUPDiscountUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEAPGROUP
     */
    'DiscountCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEAPGROUP
     */
    'DiscountDayOfMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'PaymentUnit'?: TABLEAPGROUPPaymentUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEAPGROUP
     */
    'PaymentCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEAPGROUP
     */
    'PaymentDayOfMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEAPGROUP
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEAPGROUP
     */
    'RecordRevision'?: number;
}

export const TABLEAPGROUPDefaultPaymentMethodEnum = {
    ComputerPrintedCheque: 'Computer Printed Cheque',
    CreditCard: 'Credit Card',
    DirectDebit: 'Direct Debit',
    Electronic: 'Electronic',
    LetterOfCredit: 'Letter of Credit',
    Manual: 'Manual',
    Remittance: 'Remittance',
    TelegraphicTransfer: 'Telegraphic Transfer'
} as const;

export type TABLEAPGROUPDefaultPaymentMethodEnum = typeof TABLEAPGROUPDefaultPaymentMethodEnum[keyof typeof TABLEAPGROUPDefaultPaymentMethodEnum];
export const TABLEAPGROUPDiscountUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months'
} as const;

export type TABLEAPGROUPDiscountUnitEnum = typeof TABLEAPGROUPDiscountUnitEnum[keyof typeof TABLEAPGROUPDiscountUnitEnum];
export const TABLEAPGROUPPaymentUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months'
} as const;

export type TABLEAPGROUPPaymentUnitEnum = typeof TABLEAPGROUPPaymentUnitEnum[keyof typeof TABLEAPGROUPPaymentUnitEnum];


