/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICBNMVLN
 */
export interface TABLEICBNMVLN {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNMVLN
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNMVLN
     */
    'LineID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNMVLN
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNMVLN
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNMVLN
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNMVLN
     */
    'LotNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNMVLN
     */
    'BinCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICBNMVLN
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNMVLN
     */
    'UOMMultiplier'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNMVLN
     */
    'UOMQuantityMoved'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNMVLN
     */
    'QuantityMoved'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNMVLN
     */
    'LineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICBNMVLN
     */
    'TransactionID'?: number;
}

