/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEGSRTHD
 */
export interface TABLEGSRTHD {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTHD
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTHD
     */
    'ReturnID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'RegimeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'StartDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'EndDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTHD
     */
    'GstRate'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'GstBasis'?: TABLEGSRTHDGstBasisEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGSRTHD
     */
    'Transition'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'TransDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTHD
     */
    'TransGstRate'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'ReturnStatus'?: TABLEGSRTHDReturnStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'FilingDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'FilingStatus'?: TABLEGSRTHDFilingStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGSRTHD
     */
    'Provisional'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEGSRTHD
     */
    'Calculated'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEGSRTHD
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEGSRTHD
     */
    'ReturnDate'?: string;
}

export const TABLEGSRTHDGstBasisEnum = {
    InvoiceAccruals: 'Invoice (Accruals)',
    PaymentsCash: 'Payments (Cash)',
    NotRegistered: 'Not Registered'
} as const;

export type TABLEGSRTHDGstBasisEnum = typeof TABLEGSRTHDGstBasisEnum[keyof typeof TABLEGSRTHDGstBasisEnum];
export const TABLEGSRTHDReturnStatusEnum = {
    Unposted: 'Unposted',
    Posted: 'Posted',
    Final: 'Final'
} as const;

export type TABLEGSRTHDReturnStatusEnum = typeof TABLEGSRTHDReturnStatusEnum[keyof typeof TABLEGSRTHDReturnStatusEnum];
export const TABLEGSRTHDFilingStatusEnum = {
    Unfiled: 'Unfiled',
    Pending: 'Pending',
    Filed: 'Filed',
    Manual: 'Manual'
} as const;

export type TABLEGSRTHDFilingStatusEnum = typeof TABLEGSRTHDFilingStatusEnum[keyof typeof TABLEGSRTHDFilingStatusEnum];


