/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECBFXVAR
 */
export interface TABLECBFXVAR {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLECBFXVAR
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBFXVAR
     */
    'VariationID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECBFXVAR
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBFXVAR
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBFXVAR
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBFXVAR
     */
    'BankAccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBFXVAR
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECBFXVAR
     */
    'PeriodID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECBFXVAR
     */
    'VariationType'?: TABLECBFXVARVariationTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLECBFXVAR
     */
    'VariationDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLECBFXVAR
     */
    'ExchangeRate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBFXVAR
     */
    'VariationAmount'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TABLECBFXVAR
     */
    'TransferredToGL'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLECBFXVAR
     */
    'YearNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBFXVAR
     */
    'PeriodNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECBFXVAR
     */
    'ExchangeRateRaw'?: number;
}

export const TABLECBFXVARVariationTypeEnum = {
    Unrealised: 'Unrealised',
    Realised: 'Realised',
    Variation: 'Variation'
} as const;

export type TABLECBFXVARVariationTypeEnum = typeof TABLECBFXVARVariationTypeEnum[keyof typeof TABLECBFXVARVariationTypeEnum];


