/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEARCUST
 */
export interface TABLEARCUST {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'CustomerCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'CurrencyCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARCUST
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'LastHistoryPeriod'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'CountryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'CustomerGroupCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'RegimeCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'GstOverride'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'PriceCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'DiscountScheduleCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'BillToAccountCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARCUST
     */
    'BackOrder'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'AutoAllocate'?: TABLEARCUSTAutoAllocateEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'StatementStyle'?: TABLEARCUSTStatementStyleEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'CustomerName'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'CustomerType'?: TABLEARCUSTCustomerTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'Address1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'Address2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'Address3'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'Address4'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'Address5'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'Latitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'Longitude'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'PostCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'OtherPartyCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'SalesAreaCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'SalesPersonCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'WebAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'PhoneNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'PhoneNo2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'PhoneNo3'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'BankReference'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'BankParticulars'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'Comment'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARCUST
     */
    'StopCredit'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'BusinessNo'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARCUST
     */
    'eInvoiceEnabled'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARCUST
     */
    'eCreditEnabled'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'BankAccountNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'PayerName'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARCUST
     */
    'BankThrough'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'PrimaryContactID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'EmailAddress'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'StatementEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'InvoiceEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'QuoteEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'PackingSlipEmail'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'TaxNo'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEARCUST
     */
    'OrderNoRequired'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'BranchCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'DepartmentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'Category1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'Category2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'DefaultDeliveryCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'MediaCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'CreditLimit'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'StatementAgingUnit'?: TABLEARCUSTStatementAgingUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'StatementAgingCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'Discount'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'DiscountUnit'?: TABLEARCUSTDiscountUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'DiscountCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'DiscountDayOfMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'PaymentUnit'?: TABLEARCUSTPaymentUnitEnum;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'PaymentCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'PaymentDayOfMonth'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'ModifiedUserCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'ModifiedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'ModifiedTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'EditRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'YearOpeningBalance'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'YearOpeningBalanceBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'SalesLastYear'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'SalesLastYearBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'DiscountLastYear'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'DiscountLastYearBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'DiscountPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'DiscountPeriodToDateBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'DiscountYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'DiscountYearToDateBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'PeriodOpeningBalance'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'PeriodOpeningBalanceBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'Balance3'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'Balance3Bs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'Balance2'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'Balance2Bs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'Balance1'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'Balance1Bs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'BalanceCurrent'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'BalanceCurrentBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'BalanceFuture'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'BalanceFutureBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'SalesPeriodToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'SalesPeriodToDateBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'AmountOfLastReceipt'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'DateOfLastReceipt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEARCUST
     */
    'DateOfLastSale'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'SalesYearToDate'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'SalesYearToDateBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'NumberOfInvoicesPaid'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'TotalDaysToPay'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'RecordRevision'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'BalanceTotalExclFuture'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'BalanceTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'BalanceTotalExclFutureBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'BalanceTotalBs'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEARCUST
     */
    'AverageDaysToPay'?: number;
}

export const TABLEARCUSTAutoAllocateEnum = {
    All: 'All',
    WholeBalances: 'Whole Balances',
    None: 'None'
} as const;

export type TABLEARCUSTAutoAllocateEnum = typeof TABLEARCUSTAutoAllocateEnum[keyof typeof TABLEARCUSTAutoAllocateEnum];
export const TABLEARCUSTStatementStyleEnum = {
    BalanceForward: 'Balance Forward',
    OpenItem: 'Open Item',
    None: 'None'
} as const;

export type TABLEARCUSTStatementStyleEnum = typeof TABLEARCUSTStatementStyleEnum[keyof typeof TABLEARCUSTStatementStyleEnum];
export const TABLEARCUSTCustomerTypeEnum = {
    Normal: 'Normal',
    Prospect: 'Prospect',
    Cash: 'Cash',
    OneTime: 'One-time'
} as const;

export type TABLEARCUSTCustomerTypeEnum = typeof TABLEARCUSTCustomerTypeEnum[keyof typeof TABLEARCUSTCustomerTypeEnum];
export const TABLEARCUSTStatementAgingUnitEnum = {
    Period: 'Period',
    Months: 'Months',
    Days: 'Days'
} as const;

export type TABLEARCUSTStatementAgingUnitEnum = typeof TABLEARCUSTStatementAgingUnitEnum[keyof typeof TABLEARCUSTStatementAgingUnitEnum];
export const TABLEARCUSTDiscountUnitEnum = {
    Days: 'Days',
    Weeks: 'Weeks',
    Months: 'Months'
} as const;

export type TABLEARCUSTDiscountUnitEnum = typeof TABLEARCUSTDiscountUnitEnum[keyof typeof TABLEARCUSTDiscountUnitEnum];
export const TABLEARCUSTPaymentUnitEnum = {
    Period: 'Period',
    Months: 'Months',
    Weeks: 'Weeks',
    Days: 'Days'
} as const;

export type TABLEARCUSTPaymentUnitEnum = typeof TABLEARCUSTPaymentUnitEnum[keyof typeof TABLEARCUSTPaymentUnitEnum];


