/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEICMFLINE
 */
export interface TABLEICMFLINE {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'LineID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'BatchID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFLINE
     */
    'ProductCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFLINE
     */
    'UOMCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'UOMMultiplier'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFLINE
     */
    'SerialNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFLINE
     */
    'LotNo'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFLINE
     */
    'PartType'?: TABLEICMFLINEPartTypeEnum;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICMFLINE
     */
    'LineBreak'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TABLEICMFLINE
     */
    'LineSpace'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFLINE
     */
    'LocationCode'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'UOMTransactionQuantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'TransactionQuantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFLINE
     */
    'Description'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFLINE
     */
    'Custom1'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLEICMFLINE
     */
    'Custom2'?: string;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'Weight'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'Volume'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'UOMUnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'UnitCostPrice'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'CostValueExclusive'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'LineNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'ExtendedWeight'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEICMFLINE
     */
    'ExtendedVolume'?: number;
}

export const TABLEICMFLINEPartTypeEnum = {
    Variable: 'Variable',
    Fixed: 'Fixed',
    Narrative: 'Narrative'
} as const;

export type TABLEICMFLINEPartTypeEnum = typeof TABLEICMFLINEPartTypeEnum[keyof typeof TABLEICMFLINEPartTypeEnum];


