/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECBCAT2
 */
export interface TABLECBCAT2 {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLECBCAT2
     */
    'RecNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECBCAT2
     */
    'Code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECBCAT2
     */
    'Description'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLECBCAT2
     */
    'Inactive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TABLECBCAT2
     */
    'RecordRevision'?: number;
}

