/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLECOPRTLOG
 */
export interface TABLECOPRTLOG {
    [key: string]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLECOPRTLOG
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLECOPRTLOG
     */
    'PrintID'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'DocumentCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'AccountFile'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'AccountCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'Destination'?: TABLECOPRTLOGDestinationEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'FileFormat'?: TABLECOPRTLOGFileFormatEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'CreatedDate'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'CreatedTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'CreatedUserCode'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TABLECOPRTLOG
     */
    'PrintasCopy'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'OldPrintStatus'?: TABLECOPRTLOGOldPrintStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof TABLECOPRTLOG
     */
    'NewPrintStatus'?: TABLECOPRTLOGNewPrintStatusEnum;
}

export const TABLECOPRTLOGDestinationEnum = {
    Printer: 'Printer',
    DiskFile: 'Disk File',
    MailMessage: 'Mail Message',
    ExcelWorksheet: 'Excel Worksheet',
    ExcelWorkbook: 'Excel Workbook',
    Screen: 'Screen'
} as const;

export type TABLECOPRTLOGDestinationEnum = typeof TABLECOPRTLOGDestinationEnum[keyof typeof TABLECOPRTLOGDestinationEnum];
export const TABLECOPRTLOGFileFormatEnum = {
    AdobePdf: 'Adobe PDF',
    ExcelXlsxFile: 'Excel XLSX File',
    CsvFile: 'CSV File',
    TabDelimitedFile: 'Tab Delimited File',
    QuotedCsvFile: 'Quoted CSV File',
    HtmlFile: 'HTML File',
    PdfHtmlFile: 'PDF & HTML File'
} as const;

export type TABLECOPRTLOGFileFormatEnum = typeof TABLECOPRTLOGFileFormatEnum[keyof typeof TABLECOPRTLOGFileFormatEnum];
export const TABLECOPRTLOGOldPrintStatusEnum = {
    Unprinted: 'Unprinted',
    Printed: 'Printed',
    Manual: 'Manual',
    PackingSlip: 'Packing Slip',
    Confirmed: 'Confirmed',
    Quoted: 'Quoted'
} as const;

export type TABLECOPRTLOGOldPrintStatusEnum = typeof TABLECOPRTLOGOldPrintStatusEnum[keyof typeof TABLECOPRTLOGOldPrintStatusEnum];
export const TABLECOPRTLOGNewPrintStatusEnum = {
    Unprinted: 'Unprinted',
    Printed: 'Printed',
    Manual: 'Manual',
    PackingSlip: 'Packing Slip',
    Confirmed: 'Confirmed',
    Quoted: 'Quoted'
} as const;

export type TABLECOPRTLOGNewPrintStatusEnum = typeof TABLECOPRTLOGNewPrintStatusEnum[keyof typeof TABLECOPRTLOGNewPrintStatusEnum];


