/* tslint:disable */
/* eslint-disable */
/**
 * Accredo Web Service
 * Accredo Web Service
 *
 * The version of the OpenAPI document: 7.0.13.109
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TABLEJCDTFLD
 */
export interface TABLEJCDTFLD {
    [key: `Z_${string}`]: any;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCDTFLD
     */
    'RecNo'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCDTFLD
     */
    'DeltaID'?: number;
    /**
     * 
     * @type {number}
     * @memberof TABLEJCDTFLD
     */
    'LineNo'?: number;
    /**
     * 
     * @type {string}
     * @memberof TABLEJCDTFLD
     */
    'Name'?: string;
    /**
     * 
     * @type {object}
     * @memberof TABLEJCDTFLD
     */
    'OldValue'?: object;
    /**
     * 
     * @type {object}
     * @memberof TABLEJCDTFLD
     */
    'NewValue'?: object;
}

